version: '3.8'

services:
  model_api_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: khanhnq1301/lab02:latest 
    container_name: lab_2_model_api_container
    ports:
      - "8000:8000" 
    volumes:
      - ./model.pth:/app/model.pth:ro 

    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh 
